version: "3.8"

services:
  frontend:
    build:
      context: ./frontend/todo-app
      dockerfile: Dockerfile
    container_name: todo-app-frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://todo-app-backend:80/api
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/ToDoAppApi
      dockerfile: Dockerfile
    container_name: todo-app-backend
    ports:
      - "5000:80"
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ToDoAppDB;User Id=sa;Password=yourStrongPassword123;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server-container
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_PID=${MSSQL_PID}
    ports:
      - "1433:1433"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  todo-app-db-data:
