version: "3.8"
services:
  frontend:
    build:
      context: ./frontend/todo-app  
      dockerfile: Dockerfile
    container_name: todo-app-frontend
    ports:
      - "5173:5000"  
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:5000/api  

  backend:
    build:
      context: ./backend/ToDoAppApi  
      dockerfile: Dockerfile
    container_name: todo-app-backend
    ports:
      - "5000:80"  # Expose backend port
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ToDoAppDB;User Id=sa;Password=yourStrongPassword123;

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: todo-app-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongPassword123
    ports:
      - "1433:1433"  
    networks:
      - app-network
    volumes:
      - todo-app-db-data:/var/opt/mssql  

networks:
  app-network:
    driver: bridge

volumes:
  todo-app-db-data:  
